console.log("Hello");
console.log("Hello");
// let a = "Fine working now!";
try{
    console.log(a);
}
catch{
    console.log("It is working now by using try and catch!");
}
console.log("Hello world!");
console.log("Hello world!");